sudo: required

language: go
go:
  - "1.10"

services:
  - docker

env:
  - MICRO_SERVICE=guessing/game

before_install:
  - cd MICRO_SERVICE && docker build -t $MICRO_SERVICE ./

script:
  - docker run -it $MICRO_SERVICE --entrypoint "make" $MICRO_SERVICE  test