sudo: required

language: go
go:
  - "1.10"

services:
  - docker

env:
  - MICRO_SERVICE=guessing/game

before_install:
  - cd $MICRO_SERVICE && docker build -t $MICRO_SERVICE ./

script:
  - mkdir shared & docker run -itv "$PWD/shared:/shared" --entrypoint "make" $MICRO_SERVICE travis && curl -s https://codecov.io/bash | bash -